# Generated by Django 5.0.6 on 2024-09-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.AddField(
            model_name='hotel',
            name='categories',
            field=models.ManyToManyField(to='hotel.hotelcategories'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ManyToManyField(to='hotel.hotelcity'),
        ),
    ]
