# Generated by Django 5.0.6 on 2024-09-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_categories_remove_hotel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.AddField(
            model_name='hotel',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.hotelcategories'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.hotelcity'),
        ),
    ]
