# Generated by Django 5.0.6 on 2024-09-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='users',
            new_name='user_id',
        ),
    ]
