# Generated by Django 5.0.6 on 2024-09-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_users_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='users',
        ),
    ]
