# Generated by Django 5.0.6 on 2024-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
