# Generated by Django 5.0.6 on 2024-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancle_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancle',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
